### ISSUE TITLE
Error with pnf.show_breakouts=True

### ISSUE THREAD

**Issue by salvatormundiz** [swaschke/pypnf#18]
Dear Sir 

I have problem with this line, when this line is commented every things work well I have attached my pictures and results:
```
pnf.show_breakouts=True
```
my python version is = Python 3.12.3
my code:
```
import unittest
import pandas as pd
from pypnf import PointFigureChart
import mplfinance as mpf

class TestPnfLib(unittest.TestCase):
    def test_pypnf(self):
        df = pd.pandas.read_csv('../kline_data/popcat_usdt_1m.csv')
        df.drop(columns=['s', 'p', 'a', 'Date', 'Time', 'DateTime'], inplace=True, errors='ignore')
        df['datetime'] = df['datetime'].astype(float) / 1000
        df['datetime'] = pd.to_datetime(df['datetime'], unit='s')  # Use 'ms' if it's in milliseconds
        new_order = ['datetime', 'Open', 'High', 'Low', 'Close', 'Volume']
        df = df[new_order]
        df.set_index('datetime', inplace=True)
        df = df.head(100)
        print('kline data Result:', df)
        df.to_csv('test_data.csv', index=True)
        mpf.plot(df, type='candle')

        # Convert to the required format for pypnf
        ts = {
            'date': df.index.strftime('%Y-%m-%d %H:%M').tolist(),  # Convert datetime index to string format
            'open': df['Open'].tolist(),
            'high': df['High'].tolist(),
            'low': df['Low'].tolist(),
            'close': df['Close'].tolist(),
            'volume': df['Volume'].tolist()
        }
        symbol = 'popcat_usdt' 
        pnf = PointFigureChart(ts=ts, method='cl', reversal=2, boxsize=0.002, scaling='abs', title=symbol)
        pnf.get_trendlines( length=4, mode='strong')
        print('get_trendlines:',pnf.get_trendlines())
        print(pnf)
        pnf.show_trendlines="both"
        # pnf.show_breakouts=True
        pnf.show()


if __name__ == "__main__":
    unittest.main()
```
every thing is work with this results:
```
kline data Before Pnf:                        Open    High     Low   Close     Volume
datetime                                                      
2024-09-17 17:18:00  0.7149  0.7159  0.7140  0.7152  13392.818
2024-09-17 17:19:00  0.7152  0.7185  0.7149  0.7185  15890.627
2024-09-17 17:20:00  0.7181  0.7205  0.7181  0.7191  45071.404
2024-09-17 17:21:00  0.7191  0.7224  0.7190  0.7224  20809.726
2024-09-17 17:22:00  0.7225  0.7238  0.7224  0.7238  24278.241
...                     ...     ...     ...     ...        ...
2024-09-17 18:53:00  0.7047  0.7047  0.7013  0.7020  40390.148
2024-09-17 18:54:00  0.7020  0.7033  0.7020  0.7033  22319.232
2024-09-17 18:55:00  0.7033  0.7039  0.7026  0.7039   8846.817
2024-09-17 18:56:00  0.7039  0.7047  0.7035  0.7041  12019.006
2024-09-17 18:57:00  0.7039  0.7050  0.7035  0.7035  21205.092
[100 rows x 5 columns]
get_trendlines: {'bounded': array(['external', 'internal', 'internal'], dtype='<U32'), 'type': array(['bearish resistance', 'bearish resistance', 'bullish support'],
      dtype='<U32'), 'length': array([4, 2, 1]), 'column index': array([4, 6, 7]), 'box index': array([33, 30, 20])}
Point & Figure (abs|cl) 0.002 x 2 | popcat_usdt
-----  -  -  -  -  -  -  -  -  -----
0.726  X  .  X  .  *  .  .  .  0.726
0.724  X  O  X  O  X  *  .  .  0.724
0.722  X  O  .  O  X  O  *  .  0.722
0.72   X  .  .  O  .  O  .  *  0.72
0.718  X  .  .  .  .  O  X  .  0.718
0.716  X  .  .  .  .  O  X  O  0.716
0.714  X  .  .  .  .  O  .  O  0.714
0.712  .  .  .  .  .  .  .  O  0.712
0.71   .  .  .  .  .  .  .  O  0.71
0.708  .  .  .  .  .  .  .  O  0.708
0.706  .  .  .  .  .  .  .  O  0.706
0.704  .  .  .  .  .  .  .  O  0.704
0.702  .  .  .  .  .  .  .  O  0.702
-----  -  -  -  -  -  -  -  -  -----
last trendline: bearish resistance line of length 4
printed 8/8 columns.
Ran 1 test in 1.498s
OK
```
but with this line pnf.show_breakouts=True have error:
```
Error
Traceback (most recent call last):
  File "C:\crypto\tests\test_point_figure_indicators.py", line 39, in test_pypnf
    pnf.show()
  File "C:\Users\proff\AppData\Local\Programs\Python\Python312\Lib\site-packages\pypnf\chart.py", line 2826, in show
    self._assemble_plot_chart()
  File "C:\Users\proff\AppData\Local\Programs\Python\Python312\Lib\site-packages\pypnf\chart.py", line 2782, in _assemble_plot_chart
    self._plot_breakouts()
  File "C:\Users\proff\AppData\Local\Programs\Python\Python312\Lib\site-packages\pypnf\chart.py", line 2651, in _plot_breakouts
    self.breakouts = self.get_breakouts()
                     ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\proff\AppData\Local\Programs\Python\Python312\Lib\site-packages\pypnf\chart.py", line 1308, in get_breakouts
    bo['ts index'][np.size(row_bull) + n] = self.ts['date'][self.action_index_matrix[row_bull[n], col_bull[n]]]
                                                                                     ~~~~~~~~^^^
IndexError: index 1 is out of bounds for axis 0 with size 1
```

![myCandlestick](https://github.com/user-attachments/assets/10aa4bd9-d0b0-4d74-b100-edcd27ebb604)
![myPnf](https://github.com/user-attachments/assets/da5a1771-5cad-4f5c-99ee-b0bc6eb48a06)

**Comment by salvatormundiz** [comment]
the problem is the line 1308 in chart.py under np.size(row_bear) loop
 
```
bo['ts index'][np.size(row_bull) + n] = self.ts['date'][self.action_index_matrix[row_bull[n], col_bull[n]]]
```
should be:
```
bo['ts index'][np.size(row_bull) + n] = self.ts['date'][self.action_index_matrix[row_bear[n], col_bear[n]]]
```

work well after this change! brear breakout and bull breakout detected correctly!

**Comment by fivethreeo** [comment]
Seems to be fixed in main branch, but not released
